### ISSUE TITLE
Download all the pronunciations for each German word (Feature Request)

### ISSUE THREAD

**Issue by ghost** [hrkrx/Text2WiktionarySpeech#2]
Many words on the German Wiktionary have several pronunciations. For example, the word "Katze" shows 3 pronunciations:
https://de.wiktionary.org/wiki/Katze

However, the Python script can only "grab" one pronunciation :  https://upload.wikimedia.org/wikipedia/commons/4/40/De-Katze.ogg

The other 2 pronunciations of "Katze" are not detected:

https://upload.wikimedia.org/wikipedia/commons/7/71/De-Katze2.ogg
https://upload.wikimedia.org/wikipedia/commons/7/7d/De-at-Katze.ogg

**Would it be possible to edit the Python Script as to optionally download ALL pronunciations for each word ?**

-----------------

PS. Recently, I scraped all the German Pronunciations from Forvo.com . A Dictionary for GoldenDict was made, containing around 600,000 words: https://forum.freemdict.com/t/topic/7355

_Now I would like to download ALL the audios from the German Wiktionary (700.000) to make another Dictionary for GoldenDict and distributely freely to languaqe learners._ Thanks for your kind help again !

**Comment by hrkrx** [comment]
It certainly is possible, but that is not the purpose of this repository.

in this line:
https://github.com/hrkrx/Text2WiktionarySpeech/blob/311174a25082d97bd2709ab72a2fa490090cb05a/main.py#L70
 the `next()` method only chooses a single audio file instead of multiples, but you probably need to filter a bit more to exclude the pronounciations which stand in correlation, but aren't the word you want.
